apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: events.config.dive.co
spec:
  group: config.dive.co
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                summary:
                  type: string
                descripttion:
                  type: string
                scope:
                  type: object
                  properties:
                    kind:
                      type: string
                    name:
                      type: string
                window:
                  type: object
                  properties:
                    starts:
                      type: string
                      format: date-time
                    ends:
                      type: string
                      format: date-time
  scope: Namespaced
  names:
    plural: events
    singular: event
    kind: Event
