apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: slos.config.dive.co
spec:
  group: config.dive.co
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                expression:
                  type: object
                  properties:
                    objective:
                      type: float
                    period:
                      type: string
                bound:
                  type: object
                  properties:
                    kind:
                      type: string
                    name:
                      type: string
                      enum: [Deployment]
                runbooks:
                  type: array
                  items:
                    type: string
  scope: Namespaced
  names:
    plural: slos
    singular: slo
    kind: SLO
